### ISSUE TITLE
Support custom margin sizes

### ISSUE THREAD

**Issue by zaidamazon191** [piroor/tst-indent-line#11]
The extension doesn't seem to properly work if I have a custom margins set (I made the margins bigger for better visibility). This is what it looks like

<img width="100" alt="Image" src="https://github.com/user-attachments/assets/e4211b7b-73e4-4d36-b65c-dc1090129f18" />

I have

```
tab-item[data-level][data-level="0"] tab-item-substance {
  margin-left: 5px !important;
}
tab-item[data-level][data-level="1"] tab-item-substance {
  margin-left: 50px !important;
}
tab-item[data-level][data-level="2"] tab-item-substance {
  margin-left: 90px !important;
}
tab-item[data-level][data-level="3"] tab-item-substance {
  margin-left: 130px !important;
}
tab-item[data-level][data-level="4"] tab-item-substance {
  margin-left: 170px !important;
}
tab-item[data-level][data-level="5"] tab-item-substance {
  margin-left: 210px !important;
}
tab-item[data-level][data-level="6"] tab-item-substance {
  margin-left: 250px !important;
}
tab-item[data-level][data-level="7"] tab-item-substance {
  margin-left: 290px !important;
}
tab-item[data-level][data-level="8"] tab-item-substance {
  margin-left: 330px !important;
}
tab-item[data-level][data-level="9"] tab-item-substance {
  margin-left: 370px !important;
}
tab-item[data-level][data-level="10"] tab-item-substance {
  margin-left: 410px !important;
}
tab-item[data-level][data-level="11"] tab-item-substance {
  margin-left: 450px !important;
}
tab-item[data-level][data-level="12"] tab-item-substance {
  margin-left: 490px !important;
}
tab-item[data-level][data-level="13"] tab-item-substance {
  margin-left: 530px !important;
}
tab-item[data-level][data-level="14"] tab-item-substance {
  margin-left: 570px !important;
}

```

**Comment by zaidamazon191** [comment]
The lines are assuming default spacing it seems

**Comment by zaidamazon191** [comment]
<img width="142" alt="Image" src="https://github.com/user-attachments/assets/b50e7cf6-3107-457f-bddc-5543a5c4b340" />

**Comment by piroor** [comment]
OK, how about this?:

```css
:root {
  --indent-size: 40px !important;
}
tab-item[data-level][data-level="0"] {
  --tab-indent: 5px !important;
}
tab-item[data-level][data-level="1"] {
  --tab-indent: 45px !important;
}
tab-item[data-level][data-level="2"] {
  --tab-indent: 85px !important;
}
tab-item[data-level][data-level="3"] {
  --tab-indent: 125px !important;
}
tab-item[data-level][data-level="4"] {
  --tab-indent: 165px !important;
}
tab-item[data-level][data-level="5"] {
  --tab-indent: 205px !important;
}
tab-item[data-level][data-level="6"] {
  --tab-indent: 245px !important;
}
tab-item[data-level][data-level="7"] {
  --tab-indent: 285px !important;
}
tab-item[data-level][data-level="8"] {
  --tab-indent: 325px !important;
}
tab-item[data-level][data-level="9"] {
  --tab-indent: 365px !important;
}
tab-item[data-level][data-level="10"] {
  --tab-indent: 405px !important;
}
tab-item[data-level][data-level="11"] {
  --tab-indent: 445px !important;
}
tab-item[data-level][data-level="12"] {
  --tab-indent: 485px !important;
}
tab-item[data-level][data-level="13"] {
  --tab-indent: 525px !important;
}
tab-item[data-level][data-level="14"] {
  --tab-indent: 565px !important;
}

tab-item {
  --indent-line-color: black;
  --indent-line-color-active: black;
  --indent-line-width: 1px;
  --indent-line-width-active: 3px;
}

tab-item:not(.pinned) ::part(extra-contents-by-tst-indent-line_piro_sakura_ne_jp indent-line) {
  inset-inline-start: 5px;
}
```
