### ISSUE TITLE
[Bug kinda] When making indent line bold it does not work 

### ISSUE THREAD

**Issue by haShinui** [piroor/tst-indent-line#7]
## Abstract
Hello I am trying to customize to customize TST. 
So what I want I want is a line in a color that I can decide per level (example, level 1:green, level 2:red, .... ) and I also want it bold. Thats produces 2 problems, when you the `bold 3px` the indent just crashes or doesnt show up. And I cant set a color per leveI, I can set in t general but not level specific. I use this code from your documentation a bit modified.

```css
:root {
  --custom-indent: 8px;
  --max-visual-indent: 15
}
tab-item {
    --indent-line-color-active: bold 3px blue;
}
tab-item tab-item-substance {
  margin-left: calc(var(--custom-indent) * var(--max-visual-indent)) !important;
}
tab-item[data-level][data-level="0"] tab-item-substance {
  margin-left: 0px !important;
}
tab-item[data-level][data-level="1"] tab-item-substance {
  margin-left: var(--custom-indent) !important;
  --indent-line-color: bold 3px red;
}
tab-item[data-level][data-level="2"] tab-item-substance {
  margin-left: calc(var(--custom-indent) * 2) !important;
  --indent-line-color: bold 3px green;
}
```

Also the indent lines placement is a bit random, because I want it all directly under the arrow, but sometimes its on the left or right or directly under it, see video. 
I also show my other design, where I user the border of the tabs, the outer one and the inner highlighted one, the only problem I have is that I cant go deeper then 2 level.
So if I have a level 3 there the outer border is for level 1, that makes a straight line and one for  level 3, but nothing for 2 and that cause the gapes in between which dont look good.
I also tried looking into the indent extension source code but couldn't really.
If you have any idea how to fix one of the issue let me know. I was working on it for hours and will continue

To reproduce just copy the code, I also have a theme on top but I that has not influx at all, tested it thoroughly.

https://github.com/piroor/treestyletab/assets/67230963/0f67f825-0a52-4c45-a7ef-fe3099685e6c

## Expected result
So I expect that I have lines on different level that I can each assign different color and that I can mace the lines thicker and that the line can be position under the arrow.

## Actual result
As show in the window

## Environment

 * Platform (OS): Hyprland, arch
 * Version of Firefox: 113
 * Version (or revision) of Tree Style Tab: 3.9.15, newest just update 21, Mai
